

###### headers ######

FIND_PATH( MEEARTH_INCLUDE_DIR MeCore/Export.h 
    PATHS
    ${MEEARTH_DIR}/include
    $ENV{MEEARTH_DIR}/include
    /usr/local/include
    )

    
###### libraries ######

MACRO( FIND_ME_LIBRARY MYLIBRARY MYLIBRARYNAME )
FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        ${MEEARTH_DIR}/lib
        $ENV{MEEARTH_DIR}/lib
        /usr/local/lib
        ${MEEARTH_INCLUDE_DIR}/../lib
     )
ENDMACRO(FIND_ME_LIBRARY MYLIBRARY MYLIBRARYNAME)

FIND_ME_LIBRARY( MEEARTH_MeCore_LIBRARY MeCore )
FIND_ME_LIBRARY( MEEARTH_GUITool_LIBRARY GUITool )
FIND_ME_LIBRARY( MEEARTH_MeDB_LIBRARY MeDB )
FIND_ME_LIBRARY( MEEARTH_MeQt_LIBRARY MeQt )

FIND_ME_LIBRARY( MEEARTH_MeCore_LIBRARY_DEBUG MeCored )
FIND_ME_LIBRARY( MEEARTH_GUITool_LIBRARY_DEBUG GUIToold )
FIND_ME_LIBRARY( MEEARTH_MeDB_LIBRARY_DEBUG MeDBd )
FIND_ME_LIBRARY( MEEARTH_MeQt_LIBRARY_DEBUG MeQtd )


SET( MEEARTH_FOUND "NO" )
IF( MEEARTH_INCLUDE_DIR )
    SET( MEEARTH_FOUND "YES" )
ENDIF( MEEARTH_INCLUDE_DIR )
